POST http://localhost:3000/notifications HTTP/1.1
content-type: application/json

{
  "recipientId": "7474945d-178a-461d-8765-72b4e9163a0e",
  "content": "Teste",
  "category": "teste"
}

###

GET http://localhost:3000/notifications/from/7474945d-178a-461d-8765-72b4e9163a0e HTTP/1.1

###

PATCH  http://localhost:3000/notifications/70d4b71a-4e64-4aef-94d3-cfecaafe78e3/cancel HTTP/1.1

###

PATCH  http://localhost:3000/notifications/70d4b71a-4e64-4aef-94d3-cfecaafe78e3/read HTTP/1.1

###

PATCH  http://localhost:3000/notifications/70d4b71a-4e64-4aef-94d3-cfecaafe78e3/unread HTTP/1.1

###

GET http://localhost:3000/notifications/count/from/7474945d-178a-461d-8765-72b4e9163a0e HTTP/1.1

###

GET http://localhost:3000/notifications/from/7474945d-178a-461d-8765-72b4e9163a0e HTTP/1.1

###